### ISSUE TITLE
ERROR: Initializing game failed

### ISSUE THREAD

**Issue by Redfox** [proxycapital/solana-civ-frontend#16]
Hello guys, I'm trying to run the project locally but I'm getting some errors on statup

On access http://localhost:3000/
![image](https://github.com/proxycapital/solana-civ-frontend/assets/15316761/33220a60-a4d6-4187-a4dc-edd2dd1c69e7)

When I click in "Play with Bots"
![image](https://github.com/proxycapital/solana-civ-frontend/assets/15316761/9110086d-36b3-4072-a9c1-f668751f3d65)

```
Initializing game failed: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
```

may I miss something? I'm trying to run with Phatom wallet, tried to run in main net and dev net with no success, can you guys help me?

**Comment by dwrx** [comment]
Hi @Redfox. The latest version of deployed program was not aligned with the `main` branch of frontend repo.
Can you pull the latest changes from main and retry?

**Comment by Redfox** [comment]
oh thats works @dwrx Tks!!
