### ISSUE TITLE
Add a context menu upon clicking on a city

### ISSUE THREAD

**Issue by dwrx** [proxycapital/solana-civ-frontend#31]
Current Behavior:
- If there is a unit in the city with movement points and the player clicks on it, the unit is selected.
- If the unit has no movement points or there is no unit in the city, the city modal opens.

Desired Changes:
1) Upon clicking, always open a context menu as shown in the screenshot below.
2) The menu should include the following buttons:
- "City": Opens the city modal as it currently functions.
- "Citizens": Opens a new, empty modal (this feature is under development).
- N buttons "Units in the City": Clicking on a specific unit from the context menu will select that unit without opening any other modals

To check for units in the city, retrieve the units from GameStateContext.Provider and match coordinates.

<img width="971" alt="Screenshot 2024-01-15 at 15 04 42" src="https://github.com/proxycapital/solana-civ-frontend/assets/65243529/1ca83091-c895-4c1e-b296-5e0ee3a1edff">

**Comment by Redfox** [comment]
This menu behavior is only for cases where there are units on top of a city, right?
