### ISSUE TITLE
UI Overlap Issue

### ISSUE THREAD

**Issue by dwrx** [proxycapital/solana-civ-frontend#5]
when your unit is all the way to the right of the screen the information box of the unit is covering the places where it can move

cc: CivFanatic

**Comment by dwrx** [comment]
![unit_info_gets_in_the_way_2](https://github.com/proxycapital/solana-civ-frontend/assets/65243529/1adff3e0-f921-423f-aca1-944cf0befe29)

**Comment by solciv** [comment]
Possible solution: based on the global position of the selected unit display the modal on the left / right side of the screen.

Other possible solution: add "close modal" button without losing the state of the selected unit, but maybe this solution will offer a worse UX as every time player will have to do many clicks: select unit, close the modal, attack the tile that was hidden behind the modal.

**Comment by Redfox** [comment]
@dwrx I think this issue can be closed.
